apiVersion: v1
kind: Service
metadata:
  name: lattice-mcp
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: lattice-mcp
  ports:
    - protocol: TCP
      port: {{ .Values.latticeMcp.service.port }}
      targetPort: 8080
  type: {{ .Values.latticeMcp.service.type }}
