apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.qdrant.replicaCount }}
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
        - name: qdrant
          image: "{{ .Values.qdrant.image.repository }}:{{ .Values.qdrant.image.tag }}"
          imagePullPolicy: {{ .Values.qdrant.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.qdrant.service.port }}
          volumeMounts:
            - name: qdrant-storage
              mountPath: {{ .Values.qdrant.persistence.mountPath | quote }}
          resources:
            {{- toYaml .Values.qdrant.resources | nindent 12 }}
      volumes:
        - name: qdrant-storage
          persistentVolumeClaim:
            claimName: qdrant-pvc
